services:
  front:
    container_name: front_watcher
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      # - VITE_API_URL=${VITE_API_URL}
      # - VITE_API_AUDIENCE_ID=${VITE_API_AUDIENCE_ID}
      # - VITE_API_TENANT_ID=${VITE_API_TENANT_ID}
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
      - BROKER_TOPIC=${BROKER_TOPIC}
    volumes:
      - ./front/src:/app/src
      - ./common:/app/src/common
    ports:
      - 5173:${FRONT_PORT}
    network_mode: host