// Code generated by tygo. DO NOT EDIT.

//////////
// source: binance.dto.go

export interface BinanceAggTradeDto {
  e: string;
  E: number /* int64 */;
  s: string;
  p: string;
  P: string;
  o: string;
  h: string;
  l: number /* int64 */;
  c: string;
  w: string;
  v: string;
  q: string;
  O: number /* int64 */;
  C: number /* int64 */;
  F: number /* int64 */;
  /**
   * LastTradeId                int64  `json:"L"`
   */
  n: number /* int64 */;
  a: number /* int64 */;
  A: string;
  m: boolean;
  M: boolean;
  T: number /* int64 */;
}
export interface ReverseBinanceAggTradeDto {
  event_type: string;
  event_time: number /* int64 */;
  symbol: string;
  price_change: string;
  price_change_percent?: string;
  open_price?: string;
  high_price?: string;
  last_trade_id: number /* int64 */;
  last_price?: string;
  weighted_average_price?: string;
  total_traded_bass_asset_volume?: string;
  total_traded_quot_asset_volume: string;
  statistics_open_time?: number /* int64 */;
  statistics_close_time?: number /* int64 */;
  first_trade_id: number /* int64 */;
  total_number_of_trades?: number /* int64 */;
  aggregate_trade_id: number /* int64 */;
  bestAsked_qty?: string;
  is_the_buyer_the_marker_maker: boolean;
  ignore?: boolean;
  trade_time: number /* int64 */;
}
export interface BinanceDepthDto {
  e: string;
  E: number /* int64 */;
  T: number /* int64 */;
  s: string;
  ps: string;
  /**
   * Price Level , Qty
   */
  b: string[][];
  /**
   * PRice level to be , Qty
   */
  a: string[][];
}
