// Code generated by tygo. DO NOT EDIT.

//////////
// source: broker_export.dto.go

export interface MessageDto {
  index: number /* int */;
  key: string;
  value: string;
  is_sent: boolean;
  is_handled: boolean;
}
export interface ClientDto {
  ping: PingInfo;
  topics: string[];
  is_available: boolean;
}
export interface TopicDto {
  content: MessageDto[];
  consumer_clients: ClientDto[];
  reader_index: number /* int */;
}
export type TopicMapDto = { [key: string]: TopicDto};

//////////
// source: common.go

export interface PingInfo {
  time: string /* RFC3339 */;
  is_ping_sent: boolean;
  is_pong: boolean;
  retry: number /* int */;
}
export interface Watcher {
  Conn?: any /* websocket.Conn */;
  Ping: PingInfo;
}
export interface Client {
  Conn?: any /* websocket.Conn */;
  Ping: PingInfo;
  Topics: string[];
  IsAvailable: boolean;
}
export interface Message {
  Key: string;
  Value: string;
  IsSent: boolean;
  IsHandled: boolean;
}
export interface Topic {
  Content: Message[];
  /**
   * ConsumerCients []*Client
   */
  ConsumerCients: { [key: Client | undefined]: boolean};
  ReaderIndex: number /* int */;
}
export interface PingParameter {
  IntervalAfterPing: any /* time.Duration */;
  IntervalAfterPong: any /* time.Duration */;
  MaxRetry: number /* int */;
}
export interface WatcherParameter {
  TopicContentLength: number /* int */;
  BrokerWatcherFrequenceMs: number /* int */;
}
export interface BrokerParameters {
  Ping: PingParameter;
  Watcher: WatcherParameter;
}
export interface Broker {
  Clients: { [key: Client | undefined]: boolean};
  Watcher: { [key: Watcher | undefined]: boolean};
  Topics: { [key: string]: Topic | undefined};
  Parameters: BrokerParameters;
}
